### PR TITLE
Fix cookies generation by adding path and domain

### PR DESCRIPTION
**Pull request by jellejurre**

### CODE REVIEW

**Comment by jellejurre** [comment]
Tested this myself by building the dll and running
```
using System;
using VRChat.API.Api;
using VRChat.API.Client;
using VRChat.API.Model;

// Create a configuration for us to log in
string cookie = [cookie here];
Configuration config = new Configuration();
config.ApiKey["auth"] = cookie;
// We have to identify ourselves according to the vrchat tos,
// We can't use emails here bc http header parser complains
config.UserAgent = "TestCSharpApi/0.0.1 jellejurre"; 

// Create a client to hold all our cookies :D
ApiClient client = new ApiClient();

// Create an instance of the auth api so we can verify and log in
AuthenticationApi authApi = new AuthenticationApi(client, client, config);

// We also need to create instances of the other APIs we'll need
UsersApi userApi = new UsersApi(client, client, config);
WorldsApi worldApi = new WorldsApi(client, client, config);


CurrentUser currentUser = authApi.GetCurrentUser();
Console.WriteLine("Logged in as {0}", currentUser.DisplayName);

User user = userApi.GetUser("usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469");
Console.WriteLine("Found user {0}, joined {1}", user.DisplayName, user.DateJoined);

World world = worldApi.GetWorld("wrld_ba913a96-fac4-4048-a062-9aa5db092812");
Console.WriteLine("Found world {0}, visits: {1}", world.Name, world.Visits);
```

**Comment by C0D3-M4513R** [comment]
Don't forget to actually run the section you added, so we can actually see the applied changes too.

**Comment by jellejurre** [comment]
Running generate without my changes also changes a bunch of other files. is this an issue?

**Comment by C0D3-M4513R** [comment]
Just run the for loop you added.
That should only do the changes you expect, right?

**Comment by jellejurre** [comment]
Ah, fair, didn't think of that

**Comment by jellejurre** [comment]
Pushed

**Review by C0D3-M4513R — APPROVED** [review]
lgtm, afaict

**Review by ariesclark — APPROVED** [review]

**Pull request merged**
